---

# Install Docker for Ubuntu based OS
- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

# Install Docker for RedHat 7 based OS
- include_tasks: rhel7.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

# Install Docker for RedHat 8 based OS
- include_tasks: rhel8.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'